name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: line-stricker-web-scraping

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME
    
    - name: Push image
      run: docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:${{ github.run_id }}
