name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: line-sticker-web-scraping

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - id: repository_owner
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ github.repository_owner }}
    
    - name: Build image
      run: |
        CONTAINER=ghcr.io/${{ steps.repository_owner.outputs.lowercase }}/$IMAGE_NAME:${{ github.run_id }}
        docker build . --file Dockerfile --tag $CONTAINER
    
    - name: Push image
      run: docker push $CONTAINER
